apiVersion: v1
kind: Service
metadata:
  name: {{ include "sabnzbd.fullname" . }}-clusterip
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}-clusterip
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "sabnzbd.selectorLabels" . | nindent 4 }}-clusterip
