apiVersion: v1
kind: Service
metadata:
  name: {{ include "sabnzbd.fullname" . }}-loadbalancer
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.loadBalancerService.port }}
      targetPort: {{ .Values.loadBalancerService.targetPort }}
      protocol: TCP
      name: http
  selector:
     {{- include "sabnzbd.selectorLabels" . | nindent 4 }}-loadbalancer